#!/usr/bin/env python
"""
create a shorter version of a long text file by only keeping the beginning

Usage:
  abbreviate-file -l <# output lines> <input> <output>
"""
import sys, os
import argparse


if __name__ == '__main__':
  
  argparser = argparse.ArgumentParser()
  argparser.add_argument('in_file', help='large input text file (newline delimited)')
  argparser.add_argument('out_file', help='output file')
  argparser.add_argument('-l', '--lines', default=100)
  args = argparser.parse_args()

  count = 0
  max_lines = int(args.lines)

  ifn = os.path.abspath(args.in_file)
  ofn = os.path.abspath(args.out_file)

  with open(ifn, 'r') as fi, open(ofn, 'w') as fo:
    for line in fi:
      if count == max_lines:
        break
      fo.write(line)
      count += 1
